services:

  webhook:
    build: .
    container_name: rsa-webhook

    labels:
      - traefik.enable=true

      - traefik.http.routers.webhook.rule=Host(`${WEBHOOK_DOMAIN}`)

      - traefik.http.services.webhook.loadbalancer.server.port=8000

    networks:
      - proxy


networks:
  proxy:
    external: true